In [1]:
import pandas as pd

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
data = pd.read_csv("bike_data.csv")
data.head(100)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,2
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,1
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,1
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,336,2019-08-01 00:06:08.1980,2019-08-01 00:11:44.9370,293.0,Lafayette St & E 8 St,40.730207,-73.991026,151.0,Cleveland Pl & Spring St,40.722104,-73.997249,38119,Subscriber,1989,1
96,545,2019-08-01 00:06:08.5190,2019-08-01 00:15:13.9440,325.0,E 19 St & 3 Ave,40.736245,-73.984738,3255.0,8 Ave & W 31 St,40.750585,-73.994685,29895,Subscriber,1982,1
97,683,2019-08-01 00:06:11.1850,2019-08-01 00:17:34.5660,469.0,Broadway & W 53 St,40.763441,-73.982681,422.0,W 59 St & 10 Ave,40.770513,-73.988038,18360,Subscriber,1988,1
98,196,2019-08-01 00:06:14.5090,2019-08-01 00:09:31.4510,3167.0,Amsterdam Ave & W 73 St,40.779668,-73.980930,3161.0,W 76 St & Columbus Ave,40.780184,-73.977285,27363,Customer,1969,0
99,398,2019-08-01 00:06:21.8060,2019-08-01 00:13:00.3680,3504.0,E 123 St & Lexington Ave,40.802926,-73.937900,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,26813,Subscriber,1993,1

In [3]:
# 2. Check the datatypes of your columns. 

data.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [8]:
# 3. Convert the 'tripduration' column to datetime datatype.
data["New_trip_duration"] = pd.to_datetime(data["tripduration"], unit="s")

In [10]:
# 4. Check the datatypes of your columns. 
data.dtypes
data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,New_trip_duration
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2,1970-01-01 00:06:33
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,2,1970-01-01 00:10:27
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,1,1970-01-01 00:18:52
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,1,1970-01-01 00:29:40
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,2,1970-01-01 00:25:17

In [12]:
# 5. Export the Dataframe as a new CSV file without the index.
data.to_csv(r'bike_data_processed.csv')